### ISSUE TITLE
External Contributions to FixMyBerlin?

### ISSUE THREAD

**Issue by mathebox** [FixMyBerlin/fixmy.platform#247]
**English version below**

Hi Leute!

Erstmal vielen Dank für die Idee von FixMyBerlin und dass die Plattform als Open-Source entwickelt wird!
Ich würde gerne meinen Teil zur Entwicklung beisteuern, am besten mit kleinen (unabhängigen) Aufgaben. Ich bin mir sicher, dass es hier auch noch andere Fahrrad-begeisterte Programmierer gibt, die das genau so sehen.

Das lokale Setup mit Docker lief bei mir ohne Probleme, aber nun bin ich auf der Suche nach der ersten Aufgabe.
Es wäre super, wenn dieses Repo ein bisschen mehr Hilfe für Neulinge bereitstellt, so dass der Open-Source-Gedanke aufblüht:

- **Contribution Guide bereitstellen:** als erste Anlaufstelle für neue Leute, die etwas beisteuern wollen. Der ist ja schon direkt in Github integriert ;) ([see here](1))
- **Deutsch und Englisch:** Ich kenn die Bequemlichkeit nur zu gut Tickets in der eigenen Sprache zu verfassen. Wenn Tickets und Dokumentation allerdings auf Englisch verfügbar wären, würde das eine globale Zielgruppe ansprechen. (Darum gibt's das Ticket auch unten nochmal auf Englisch.) Wichtig wäre es eine Sprache durchgängig zu verwenden.
- **Ticketbeschreibungen:** Ich habe bemerkt, dass Ticket häufig nur aus einer Überschrift und ein paar Schlagwörtern bestehen. Bestimmt habt ihr separate Treffen bei denen die Tickets ausführlich besprochen werden. Allerdings bleiben so Details für andere verborgen.
- **Aufgaben für Einsteiger:** Es wäre super, wenn es Tickets geben würde, die sich gut zum Einstieg in den Code eignen würden. Spontan fällt mir ein, dass Einsteiger beispielsweise zusätzliche Tests schreiben könnten, die euch dann helfen die Produktqualität stabil zu halten und Regressionen vermeiden können.

Was haltet ihr davon? 

Für mehr einen besseren Rundverkehr in Berlin und weiteren Städten! 💚🚴‍♂️

<hr/>

Hi folks,

First of all thanks for creating FixMyBerlin and making the source code available for the public!
Second, I would like to help to build and enhance the platform, preferably by working on smaller tasks. I'm sure other cyclist-friendly programmers would like to contribute as well.

The local setup is quite simple when using docker. However, now I'm looking for some beginner tasks.
To embrace the open-source approach, it would be great if you could provide some guidance:

- **Add Contribution Guide:** As the first reference for people who would like to contribute. This is tightly integrated on Github ;) ([see here](1))
- **German vs English:** I know the convenience of writing issues in your native language firsthand. But providing issues and documentation in English would include the global audience. (That's why this issue is written in German and English.) I find it beneficial to use one language consistently.
- **Issue descriptions:** I noticed most of your issues mostly only consist of a title and some buzzwords for reference. Certainly, you have had meetings where you discussed these issues in more detail. But for all others, these details are hidden.
- **Beginner tasks:** I would love to see some issues labeled especially for beginners. Of the top of my head, I think that expanding the test suite would be for first contributions while helping you to ensure good product quality and prevent regressions.

Let me know what you think.

For more cyclists in Berlin and many other cities! 💚🚴‍♂️

[1]: https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by geomC** [comment]
Hi Max,

thanks for your input, it is appreciated!
I don't contribute full-time so I talked to @hekele who owns the repo:
We are very happy to (further) open up the development process for external contributions.

As you habe guessed we do have a regular meeting in which we coordinate the development. 
We will put this point on the agenda of the next meeting.

With the feedback I got I can already comment on the points you stated:

> Add contribution guide.

Will definitly be done soon!

> Issue descriptions
> German vs English

You have a point there, but writing every issue in english or stating every detail of a task is not possible at the moment since time schedules within development sprints are a bit narrow these days. 
FixMyBerlin is driven by project-funding and up to now we did not really have regular external committers who could pick up tasks. But I guess it is a chicken-and-egg-problem.

IMHO more detailed, english issue descriptions will expecially make sense for 
> Beginner tasks

Yep, we will definitly try to identify and mark tasks as using the "good first issue" label.
Those will propably be 
* bug fixes
* smaller features
* (as you said) automated tests. We are currently looking into adding e2e tests to the fronted to get a more stable product, see 
https://github.com/FixMyBerlin/fixmy.platform/issues/125 and
https://github.com/FixMyBerlin/fixmy.platform/issues/239. Once we 
  * figured out how to integrate this in the overall development process (CI) and once
  * the test setup has been merged to /develop
this is an excellant task to work on collaboratively

As I said, we will discuss this in our next review/planning meeting and get back to you  - respectivley start writing tasks open to external contribution.

**Comment by geomC** [comment]
So we have sticked our heads together. We are happy to open up smaller features and bugfixes for external contributors by writting detailed issues that get labeled as starter-issues.
For ideas regarding rather large features, we would rather get together in our Slack beforehand and discuss if/how a contribution is possible. We will write this in the contribution guide.

We will set the contribution guide as well as issues for smaller features within the next couple of weeks.
@mathebox If you want you can also already take part in this process. We will incrementally shape the guide in an extra branch in this repository. I will post the branch here once I have developed a first draft.

**Comment by geomC** [comment]
Moved to https://github.com/FixMyBerlin/fixmy.platform/issues/253, closing this

**Comment by geomC** [comment]
Hey @mathebox , checkout https://github.com/FixMyBerlin/fixmy.frontend/blob/develop/CONTRIBUTING.md.
