### ISSUE TITLE
iPad: API Link cannot be clicked

### ISSUE THREAD

**Issue by tordans** [FixMyBerlin/fixmy.platform#391]
#### Issue description
On the iPad, I cannot click the link to the API since it is overlapped by the FMB-Logo, which is also a Link.

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/111561/87216691-533d3700-c342-11ea-9bfb-34ab30a95d8f.jpeg)
![image](https://user-images.githubusercontent.com/111561/87216692-57695480-c342-11ea-8817-b588e3367a79.jpeg)

**Comment by ciex** [comment]
Thank you @tordans! I will look into this.

**Comment by s-pic** [comment]
Reproduced using an Ipad simulator (https://appetize.io).
![image](https://user-images.githubusercontent.com/12786207/88486133-e2ba2b00-cf7b-11ea-93c7-3170581eac8c.png)

I wonder why this happens. If I emulate a mobile device in chrome with a viewport height smaller than what the navbar needs, 
everything looks fine.

![image](https://user-images.githubusercontent.com/12786207/88486180-33318880-cf7c-11ea-8ef5-79617681f578.png)

Looks like some safari-specific lack of support for css props.

**Comment by s-pic** [comment]
Since I am a windows user without an Ipad, I tried to dry-debug this by doing some research. 
At first I assumed a bug relating _flex_, which is not the case. There seems to be no open issue in recent safari versions, see https://github.com/philipwalton/flexbugs.

Then I checked [Bootstrap´s Wall of Browser Bugs](https://getbootstrap.com/docs/4.4/browser-bugs/) and stumbled upon this:
![image](https://user-images.githubusercontent.com/12786207/88487160-0339b380-cf83-11ea-8e65-64a8e1e8c1d2.png)
The orientation shown by @tordans should be landscape, and we do use fixed positioning in the menu.

![image](https://user-images.githubusercontent.com/12786207/88487178-1fd5eb80-cf83-11ea-9183-eea13f39df3e.png)

I will further look into this within the next days.
