### ISSUE TITLE
UX: Add loading indicator to reports overview map

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#399]
**What's the problem you want solved?**

When I load a reports overview map (e.g. https://radbuegel-aachen.de/meldungen/karte), it might take more than 2 or 3 seconds until markers are appearing on the map. This loading process should be indicated.

**Is there a solution you'd like to recommend?**

* show loading spinner, hide on tile load events, see https://github.com/mapbox/mapbox-gl-js/issues/6178#issuecomment-366394651

**Comment by ciex** [comment]
This has been a problem indeed. However, instead of waiting for tile load, I guess the loading indicator should be displayed until the API call for reports has completed, right? It should display the BigLoader component until then. Caching the reports request in the backend would also be desirable but we don't have a good established cache invalidation pattern yet that would allow us to do this for user submitted data.

**Comment by s-pic** [comment]
You are right about the metrics. I am going to create a PR.

**Comment by s-pic** [comment]
As discussed

- the Loader goes next to the map (as opposed to the current state, where the map contains the loader) and gets a position centered in the viewport (as opposed to centered in the map)
- we will use an extended version of `BigLoader` that uses absolute positioning to achieve a centered position relative to the viewport (as opposed to flex-based positioning)  **to not influence other consumers of the BigLoader** which rely on an implementation that uses flex-box to align the center to certain container element dimensions

**Comment by s-pic** [comment]
- [ ] find a proper way to cope with default props, don't disable eslint
